# Generated by Django 3.1.7 on 2021-04-03 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='data',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Time', models.DateTimeField()),
                ('temperature', models.IntegerField()),
                ('dew_point', models.IntegerField()),
                ('wind_speed', models.IntegerField()),
                ('wind_gust', models.IntegerField()),
            ],
        ),
    ]
