# Generated by Django 3.1.7 on 2021-04-05 11:18

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_input', '0002_remove_data_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='data',
            name='Time',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
    ]
