# Generated by Django 3.1.7 on 2021-04-05 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_input', '0003_data_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='data',
            name='Time',
            field=models.DateTimeField(blank=True),
        ),
    ]
