# Generated by Django 3.1.7 on 2021-04-05 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_input', '0004_auto_20210405_1121'),
    ]

    operations = [
        migrations.AlterField(
            model_name='data',
            name='Time',
            field=models.CharField(max_length=50),
        ),
    ]
